package modelo;
// Generated 08-jul-2014 18:39:14 by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Empleado generated by hbm2java
 */
@Entity
@Table(name="empleado"
    ,catalog="teide2014"
)
public class Empleado  implements java.io.Serializable {


     private Integer idEmpleado;
     private Date fechaAlta;
     private int idPuesto;
     private String nombre;
     private double salario;

    public Empleado() {
    }

	
    public Empleado(int idPuesto, String nombre, double salario) {
        this.idPuesto = idPuesto;
        this.nombre = nombre;
        this.salario = salario;
    }
    public Empleado(Date fechaAlta, int idPuesto, String nombre, double salario) {
       this.fechaAlta = fechaAlta;
       this.idPuesto = idPuesto;
       this.nombre = nombre;
       this.salario = salario;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idEmpleado", unique=true, nullable=false)
    public Integer getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(Integer idEmpleado) {
        this.idEmpleado = idEmpleado;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaAlta", length=10)
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }

    
    @Column(name="idPuesto", nullable=false)
    public int getIdPuesto() {
        return this.idPuesto;
    }
    
    public void setIdPuesto(int idPuesto) {
        this.idPuesto = idPuesto;
    }

    
    @Column(name="nombre", nullable=false, length=250)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="salario", nullable=false, precision=22, scale=0)
    public double getSalario() {
        return this.salario;
    }
    
    public void setSalario(double salario) {
        this.salario = salario;
    }




}


